// Question Object
let questions = [
    {   questionNumber: "1",
        questionContent: "Is your Grandma's haunted attic funky?",
        answerOne: "I've never seen a ghost in there",
        answerTwo: "An attic? What am I, made of money??",
        answerThree: "Totally! It's like Studio 54.",
        answerFour: "No, the ghost is an excellent housekeeper.",
        correctAnswer: "No, the ghost is an excellent housekeeper.",
    },

    {   questionNumber: "2",
        questionContent: "Is Parliament funky?",
        answerOne: "Yes, the Brits can totally get down!",
        answerTwo: "Maybe? I'm more of a constitutional monarchy kind of person.",
        answerThree: "Duh, beam me to the Mothership!",
        answerFour: "No, I don't smoke.",
        correctAnswer: "Duh, beam me to the Mothership!",
    },

    {   questionNumber: "3",
        questionContent: "Is a Farmhouse Ale funky?",
        answerOne: "No, drunk cows are all left feet.",
        answerTwo: "I turn 21 next week.",
        answerThree: "Embrace the funk, baby!",
        answerFour: "Where is the farmhouse?",
        correctAnswer: "Embrace the funk, baby!",
    },

    {   questionNumber: "4",
        questionContent: "Is belly button lint funky?",
        answerOne: "Depends on the sweater.",
        answerTwo: "Belly button? I was hatched from an egg.",
        answerThree: "Yes, I've been wearing these sweatpants for days.",
        answerFour: "Innie or outie?",
        correctAnswer: "Yes, I've been wearing these sweatpants for days.",
    },

    {   questionNumber: "5",
        questionContent: "Is Limburger cheese funky?",
        answerOne: "Charles was more of a ham and swiss guy.",
        answerTwo: "Is the Pope Catholic?",
        answerThree: "Only on a hamburger.",
        answerFour: "Dang, that cheese has some stank on it!",
        correctAnswer: "Dang, that cheese has some stank on it!",
    },

    {   questionNumber: "6",
        questionContent: "Is Kenny G funky?",
        answerOne: "Funky? No. But pretty fly?",
        answerTwo: "Not with that intonation.",
        answerThree: "Ask John Zorn.",
        answerFour: "Yeah, smooth jazz always gets me going.",
        correctAnswer: "Not with that intonation.",
    },

    {   questionNumber: "7",
        questionContent: "Is George Clinton funky?",
        answerOne: "...I think you mean Bill Clinton",
        answerTwo: "I've seen Good Burger!",
        answerThree: "Like an Atomic Dog",
        answerFour: "Didn't I already answer this question?",
        correctAnswer: "Like an Atomic Dog",
    },

    {   questionNumber: "8",
        questionContent: "Is a flooded crawlspace funky?",
        answerOne: "Yes, you can never get it dry again.",
        answerTwo: "No, you can always get it dry again.",
        answerThree: "Yes, makes a great swimming pool.",
        answerFour: "No, I would describe it as more musty.",
        correctAnswer: "No, I would describe it as more musty.",
    },

    {   questionNumber: "9",
        questionContent: "Is Will Ferrell funky?",
        answerOne: "Yes",
        answerTwo: "Sometimes",
        answerThree: "The baseball player?",
        answerFour: "I think you mean \"funny\"",
        correctAnswer: "I think you mean \"funny\"",
    },

    {   questionNumber: "10",
        questionContent: "Is Accrual Based Accounting funky?",
        answerOne: "How long is this quiz?",
        answerTwo: "No",
        answerThree: "I don't know what that is",
        answerFour: "Yes, have you met Barb in accounts receivable?",
        correctAnswer: "I don't know what that is",
    },

];