// Question Object
let questions = [
    {   questionNumber: "1",
        questionContent: "Is this question one?",
        answerOne: "No",
        answerTwo: "Yes",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "Yes",
    },

    {   questionNumber: "2",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "No",
    },

    {   questionNumber: "3",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "4",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "5",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "6",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "7",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "8",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "9",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

    {   questionNumber: "10",
        questionContent: "Is this question one?",
        answerOne: "Yes",
        answerTwo: "No",
        answerThree: "You've got to be kidding me",
        answerFour: "I've had it up to here!",
        correctAnswer: "answerTwo",
    },

];